[project]
name = "gold"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polygon-api-client>=1.16.3",
    "pytz>=2025.2",
    "yfinance>=0.2.66",
]
